run:
  tests: true
  fast: true
  build-tags:
    - golangci
  skip-dirs:
    - .github
    - .vscode
  allow-parallel-runners: true

output:
  format: colored-line-number
  sort-results: true

linters:
  # Enable all the linters except the ones disabled below
  enable-all: true
  disable:
  # Disable deprecated/abandoned linters
  - golint
  - interfacer
  - ifshort
  - scopelint
  - exhaustivestruct
  - maligned
  - nosnakecase
  - varcheck
  - deadcode
  # Disabled because of generics
  - contextcheck
  - rowserrcheck
  - sqlclosecheck
  - structcheck
  - wastedassign
  # Disable due to test and mock private functions
  - testpackage
