// Code generated by "stringer -type TaskSegmentType -output segment_type.go"; DO NOT EDIT.

package todotxt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SegmentIsCompleted-1]
	_ = x[SegmentCompletedDate-2]
	_ = x[SegmentPriority-3]
	_ = x[SegmentCreatedDate-4]
	_ = x[SegmentTodoText-5]
	_ = x[SegmentContext-6]
	_ = x[SegmentProject-7]
	_ = x[SegmentTag-8]
	_ = x[SegmentDueDate-9]
}

const _TaskSegmentType_name = "SegmentIsCompletedSegmentCompletedDateSegmentPrioritySegmentCreatedDateSegmentTodoTextSegmentContextSegmentProjectSegmentTagSegmentDueDate"

var _TaskSegmentType_index = [...]uint8{0, 18, 38, 53, 71, 86, 100, 114, 124, 138}

func (i TaskSegmentType) String() string {
	i -= 1
	if i < 0 || i >= TaskSegmentType(len(_TaskSegmentType_index)-1) {
		return "TaskSegmentType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TaskSegmentType_name[_TaskSegmentType_index[i]:_TaskSegmentType_index[i+1]]
}
