# This workflow runs the unit test (`go test ./...`) on vaious platforms,
# such as: Linux, macOS and Windows.
name: PlatformTests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    name: Unit test

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1'
          check-latest: true
          # Use cache if go.mod is not changed
          cache: true

      - name: Run unit test
        run: |
          go mod download
          go test -race -v ./...